### ISSUE TITLE
Invalid algorithm 

### ISSUE THREAD

**Issue by erotundo** [giosil/xades#1]
Hello!

I'm trying to user your project but get all the time invalid algorithm selected.

So i don't know if it's the problem of the certificate file installed on windows or where is the problem.

Thanks!

**Comment by giosil** [comment]
Hi, I can't tell you. This has never happened to me.
Try debugging to see exactly where it goes wrong.
You probably don't find the algorithm here:

rsaPKCS1SignatureFormatter.SetHashAlgorithm("SHA256");

Check the runtime of .Net version.
The code is trivial. There are no "magic" inside.
Greetings,
